version: "3.8"

services:
  byeclocking:
    build: .
    container_name: byeclocking
    restart: unless-stopped
    environment:
      - TZ=Europe/Madrid
    volumes:
      - ./configs:/app/configs
      - ./logs:/app/logs
